// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function GetSnapshot():Promise<engine.Snapshot>;

export function ListOutputDevices():Promise<Array<engine.OutputDevice>>;

export function Rename(arg1:number,arg2:string):Promise<void>;

export function Running():Promise<boolean>;

export function SetLatencyProfile(arg1:number,arg2:number):Promise<string>;

export function SetMasterVolume(arg1:number):Promise<void>;

export function SetMuted(arg1:number,arg2:boolean):Promise<void>;

export function SetOutputDevice(arg1:string,arg2:string):Promise<string>;

export function SetSolo(arg1:number,arg2:boolean):Promise<void>;

export function SetVolume(arg1:number,arg2:number):Promise<void>;

export function Start():Promise<string>;

export function Stop():Promise<void>;

export function Version():Promise<string>;
