// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function ListOutputDevices() {
  return window['go']['main']['App']['ListOutputDevices']();
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function Running() {
  return window['go']['main']['App']['Running']();
}

export function SetLatencyProfile(arg1, arg2) {
  return window['go']['main']['App']['SetLatencyProfile'](arg1, arg2);
}

export function SetMasterVolume(arg1) {
  return window['go']['main']['App']['SetMasterVolume'](arg1);
}

export function SetMuted(arg1, arg2) {
  return window['go']['main']['App']['SetMuted'](arg1, arg2);
}

export function SetOutputDevice(arg1, arg2) {
  return window['go']['main']['App']['SetOutputDevice'](arg1, arg2);
}

export function SetSolo(arg1, arg2) {
  return window['go']['main']['App']['SetSolo'](arg1, arg2);
}

export function SetVolume(arg1, arg2) {
  return window['go']['main']['App']['SetVolume'](arg1, arg2);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
